name: build the system
on: [push]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Get dependencies
        run: sudo apt-get install libpango1.0-dev libgtk-3-dev libgdk-pixbuf2.0-dev
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: target/debug/chip8